packages:
  # include packages in subfolders (e.g. apps/ and packages/)
  - 'packages/docs'
  - 'packages/core/api'
  - 'packages/core/interface'
  - 'packages/core/web'
  - 'packages/libs/common'
  - 'packages/libs/calendar-plan/api'
  - 'packages/libs/calendar-plan/interface'
  - 'packages/libs/calendar-plan/web'
  - 'packages/libs/dates'
  - 'packages/libs/testing'
  - 'packages/libs/time-series/api'
  - 'packages/libs/time-series/interface'
  - 'packages/libs/time-series/web'
  - 'packages/libs/timers/api'
  - 'packages/libs/timers/interface'
  - 'packages/libs/ui'
  - 'packages/libs/devtools'
  - 'packages/applications/pwa'
  - 'packages/applications/server'
  - 'packages/features/activities/web'
  - 'packages/features/habits/api'
  - 'packages/features/habits/interface'
  - 'packages/features/habits/web'
  - 'packages/features/journals/api'
  - 'packages/features/journals/interface'
  - 'packages/features/journals/web'
  - 'packages/features/legal/api'
  - 'packages/features/legal/interface'
  - 'packages/features/legal/web'
  - 'packages/features/milestones/api'
  - 'packages/features/milestones/interface'
  - 'packages/features/milestones/web'
  - 'packages/features/analytics/api'
  - 'packages/features/analytics/interface'
  - 'packages/features/analytics/web'
  - 'packages/features/tasks/api'
  - 'packages/features/tasks/interface'
  - 'packages/features/tasks/web'
