FROM nginx:latest

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom configuration file
COPY nginx.conf.dist /etc/nginx/conf.d/

# Copy your static files to the container
COPY packages/web/dist /usr/share/nginx/html/

# Copy configuration
COPY docker/web.env /usr/share/nginx/html/.env
