global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo1:9100', 'mongo2:9100', 'mongo3:9100']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
