on:
  pull_request:
    branches: [ "main", "development" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Base Branch Context
        env:
          BASE_BRANCH: ${{github.base_ref}}
        run: echo "$BASE_BRANCH"

      - name: Dump Branch Context
        env:
          BRANCH: ${{github.head_ref }}
        run: echo "$BRANCH"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build devtools
        run: pnpm -F @lyvely/devtools build

      - run: "git branch --track ${{github.base_ref}} origin/${{github.base_ref}}"
      - run: "git branch --track ${{github.head_ref}} origin/${{github.head_ref}}"
      - run: pnpm nx run-many -t build --all --exclude=@lyvely/docs
      - run: pnpm nx affected:lint --base=${{ github.base_ref }} --head=${{ github.head_ref }}
      - run: pnpm nx affected:test --base=${{  github.base_ref }} --head=${{ github.head_ref }}
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Base Branch Context
        env:
          BASE_BRANCH: ${{github.base_ref}}
        run: echo "$BASE_BRANCH"

      - name: Dump Branch Context
        env:
          BRANCH: ${{github.head_ref }}
        run: echo "$BRANCH"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build devtools
        run: pnpm -F @lyvely/devtools build

      - run: "git branch --track ${{github.base_ref}} origin/${{github.base_ref}}"
      - run: "git branch --track ${{github.head_ref}} origin/${{github.head_ref}}"
      - run: pnpm nx run-many -t build --all --exclude=@lyvely/docs
      - run: pnpm nx affected:test --base=${{  github.base_ref }} --head=${{ github.head_ref }}
